### ISSUE TITLE
A crash bug is triggered when using GroupBy while querying FIELD KEY CARDINALITY.

### ISSUE THREAD

**Issue by LingweiKuang** [influxdata/influx-cli#547]
#### Steps to reproduce

In the latest version of InfluxDB, if we have an organization named "organization", we can use the Influx client to execute the following commands to create a bucket and write the specified data into that bucket.

```
influx bucket delete --name db0
influx bucket create --name db0 --org organization

influx write \
  --bucket db0 \
  --precision s "
t0,t0_tag0=initTag t0_f0=0u 1641024000
t0,t0_tag0=initTag t0_f0=1u 1641024001
t0,t0_tag1=initTag t0_f0=0u 1641024000"
```

Next, we use the `Influx v1 shell` command to enter the Influx shell backend and execute three types of query statements:

```
# query 1
SHOW FIELD KEY CARDINALITY FROM db0.autogen.t0

# query 2
SHOW FIELD KEY CARDINALITY FROM db0.autogen.t0 WHERE ('a' !=  (t0_tag0))

# query 3
SHOW FIELD KEY CARDINALITY FROM db0.autogen.t0 WHERE ('a' !=  (t0_tag0)) GROUP BY t0_tag0
```

#### Expected behaviour

The above query statements should execute successfully and return the corresponding results.

#### Actual behaviour

When executing query1 and query2, the Influx shell is able to return the correct results. However, when executing query3, the Influx shell **exits unexpectedly** and reports the following error:

```
panic: runtime error: slice bounds out of range [:-2] [recovered]
        panic: close of nil channel

goroutine 1 [running]:
github.com/charmbracelet/bubbletea.(*standardRenderer).kill.func1()
        /go/pkg/mod/github.com/charmbracelet/bubbletea@v0.21.0/standard_renderer.go:91 +0x1b
sync.(*Once).doSlow(0xe2a380?, 0xc000110020?)
        /go/src/sync/once.go:74 +0xbf
sync.(*Once).Do(...)
        /go/src/sync/once.go:65
github.com/charmbracelet/bubbletea.(*standardRenderer).kill(0xc00021c960)
        /go/pkg/mod/github.com/charmbracelet/bubbletea@v0.21.0/standard_renderer.go:90 +0x92
github.com/charmbracelet/bubbletea.(*Program).shutdown(0xc00014e790, 0x0?)
        /go/pkg/mod/github.com/charmbracelet/bubbletea@v0.21.0/tea.go:584 +0x42
github.com/charmbracelet/bubbletea.(*Program).StartReturningModel.func3()
        /go/pkg/mod/github.com/charmbracelet/bubbletea@v0.21.0/tea.go:369 +0x45
panic({0xc6dbe0?, 0xc000148318?})
        /go/src/runtime/panic.go:920 +0x270
github.com/influxdata/influx-cli/v2/clients/v1_shell.Model.Init({{0xc0002a4a6c, 0x2}, 0xc00028fbc0, 0x1, 0x1, 0x1, 0x1, {0xc00028fbf0, 0x1, 0x1}, ...})
        /root/project/clients/v1_shell/table_model.go:180 +0x4b0
github.com/charmbracelet/bubbletea.(*Program).StartReturningModel(0xc00014e790)
```
We suspect that this is a crash bug.

#### Environment info

Influx CLI dev (git: none) build_date: 2023-04-28T14:24:14Z

InfluxDB OSS v2.7.10 (git: f302d97)

Linux 5.15.0-94-generic x86_64

**Comment by srebhan** [comment]
@LingweiKuang thanks for reporting this crash, we will take a look but it might take some time...

**Comment by karel-rehor** [comment]
I've managed to reproduce this following the user's example as well as following a related case.  

```
$ influx bucket delete --name test
$ influx bucket create --name "test" --org "my-org"

$ influx write \
  --bucket test \
  --precision s "
tagless val=-2i,state=\"on\" 1731069801
tagless val=-1i,state=\"off\" 1731069791
tagless val=0i,state=\"on\" 1731069781
tagless val=1i,state=\"off\" 1731069771
tagless val=2i,state=\"on\" 1731069761"
```
Note above that state is a field not a tag, so the measurement has no tags.  

Then... 
`influx v1 shell --host http://localhost:9999 --token my-token --http-debug`

And in the shell. 

```
> SELECT * FROM test..tagless GROUP BY state
```
The http transaction shows 

```
2024/11/08 13:52:07 
GET /query?db=&epoch=ns&q=SELECT+%2A+FROM+test..tagless+GROUP+BY+state&rp= HTTP/1.1
Host: localhost:9999
User-Agent: influx/dev (linux) Sha/none Date/2024-11-08T12:40:39Z
Accept: application/json
Authorization: Token my-token
Accept-Encoding: gzip


2024/11/08 13:52:07 
HTTP/1.1 200 OK
Content-Length: 276
Content-Type: application/json
Date: Fri, 08 Nov 2024 12:52:07 GMT
Vary: Accept-Encoding
X-Influxdb-Build: OSS
X-Influxdb-Version: v2.7.10

{"results":[{"statement_id":0,"series":[{"name":"tagless","tags":{"state":""},"columns":["time","state","val"],"values":[[1731069761000000000,"on",2],[1731069771000000000,"off",1],[1731069781000000000,"on",0],[1731069791000000000,"off",-1],[1731069801000000000,"on",-2]]}]}]}
```
Note that the `tags` element has a KeyValue pair with a `state` key having an empty value. 

This results in the `bubbletea` model having an empty tagline.  

The exception thrown is similar
```
panic: runtime error: slice bounds out of range [:-2] [recovered]
	panic: close of nil channel

goroutine 1 [running]:
github.com/charmbracelet/bubbletea.(*standardRenderer).kill.func1()
	/home/karl/.gvm/pkgsets/go1.22.1/global/pkg/mod/github.com/charmbracelet/bubbletea@v0.21.0/standard_renderer.go:91 +0x1b
sync.(*Once).doSlow(0xe58220?, 0xc000124048?)
	/home/karl/.gvm/gos/go1.22.1/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
	/home/karl/.gvm/gos/go1.22.1/src/sync/once.go:65
github.com/charmbracelet/bubbletea.(*standardRenderer).kill(0xc00012a320)
	/home/karl/.gvm/pkgsets/go1.22.1/global/pkg/mod/github.com/charmbracelet/bubbletea@v0.21.0/standard_renderer.go:90 +0x92
github.com/charmbracelet/bubbletea.(*Program).shutdown(0xc0004e8000, 0x5?)
	/home/karl/.gvm/pkgsets/go1.22.1/global/pkg/mod/github.com/charmbracelet/bubbletea@v0.21.0/tea.go:584 +0x42
github.com/charmbracelet/bubbletea.(*Program).StartReturningModel.func3()
	/home/karl/.gvm/pkgsets/go1.22.1/global/pkg/mod/github.com/charmbracelet/bubbletea@v0.21.0/tea.go:369 +0x45
panic({0xc92ea0?, 0xc00035a0a8?})
	/home/karl/.gvm/gos/go1.22.1/src/runtime/panic.go:770 +0x132
github.com/influxdata/influx-cli/v2/clients/v1_shell.Model.Init({{0xc000322130, 0x7}, 0xc0003101e0, 0x1, 0x1, 0x1, 0x1, {0xc0000ba270, 0x5, 0x5}, ...})
	/home/karl/bonitoo/prjs/github.com/influxdata/influx-cli/clients/v1_shell/table_model.go:186 +0x4b0
```
(Note I've been playing with `table_model.go` so there is a slight discrepancy in the line number.)

I propose setting a standard value like "N/A" when a tag key results in an empty value.
